### ISSUE TITLE
As a user, I'd like to buy the things I need to make the drink

### ISSUE THREAD

**Issue by mjpalacios25** [mjpalacios25/Cocktail-Party#16]
Use a shopping API (Amazon API) to link to products you can buy.

**Comment by daltoncampos** [comment]
done
added this link to example.html ( <a target="_blank" href="https://www.amazon.com/Crystal-Cocktail-Mixing-Glass-Set/dp/B072J85F1L/ref=sr_1_9?keywords=mixing+glass&amp;qid=1577421299&amp;s=home-garden&amp;sr=1-9&_encoding=UTF8&tag=daltoncampo0c-20&linkCode=ur2&linkId=28c0c499c812f8633df74c3f2ee7d219&camp=1789&creative=9325">Mixing Kit</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=daltoncampo0c-20&l=ur2&o=1" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> )
